#!/bin/bash
# Install Nock 4K kernel
python -c "
import nock_kernel
import os
import subprocess

spec_dir = os.path.join(os.path.dirname(nock_kernel.__file__), 'kernelspec')
subprocess.run(['jupyter', 'kernelspec', 'install', spec_dir, '--user', '--name', 'nock'], check=True)
"

# Install Nockasm kernel
python -m nockasm_kernel.install