#!/bin/bash
# Install Nock kernel
python -c "
import nock_kernel
import os
import subprocess

spec_dir = os.path.join(os.path.dirname(nock_kernel.__file__), 'kernelspec')
subprocess.run(['jupyter', 'kernelspec', 'install', spec_dir, '--user', '--name', 'nock'], check=True)
"